-- ============================================================================
-- Allineamento una tantum dello schema del DB di SVILUPPO a quello di prod
-- (differenze rilevate il 2026-09-23). Si esegue una sola volta, sul DB di
-- dev, con il workflow Apply_SQL_to_dev_DB (che poi ricopia i dati da prod).
-- ============================================================================

BEGIN;

-- draft.id: in prod e' IDENTITY, in dev un bigint senza default
ALTER TABLE public.draft ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.draft', 'id'),
              COALESCE((SELECT max(id) FROM public.draft), 0) + 1, false);

-- draft: detentori obbligatori come in prod
ALTER TABLE public.draft ALTER COLUMN detentore_att       SET NOT NULL;
ALTER TABLE public.draft ALTER COLUMN detentore_originale SET NOT NULL;

-- prestito.tipo_prestito: enum in prod, varchar in dev
ALTER TABLE public.prestito
  ALTER COLUMN tipo_prestito TYPE public.tipo_prestito
  USING tipo_prestito::public.tipo_prestito;

-- FK verso squadra(nome) con ON UPDATE CASCADE, come in prod
ALTER TABLE public.draft DROP CONSTRAINT draft_detentore_att_fkey,
  ADD CONSTRAINT draft_detentore_att_fkey FOREIGN KEY (detentore_att) REFERENCES public.squadra(nome) ON UPDATE CASCADE;
ALTER TABLE public.draft DROP CONSTRAINT draft_detentore_originale_fkey,
  ADD CONSTRAINT draft_detentore_originale_fkey FOREIGN KEY (detentore_originale) REFERENCES public.squadra(nome) ON UPDATE CASCADE;
ALTER TABLE public.prestito DROP CONSTRAINT prestito_squadra_prestante_fkey,
  ADD CONSTRAINT prestito_squadra_prestante_fkey FOREIGN KEY (squadra_prestante) REFERENCES public.squadra(nome) ON UPDATE CASCADE;
ALTER TABLE public.prestito DROP CONSTRAINT prestito_squadra_ricevente_fkey,
  ADD CONSTRAINT prestito_squadra_ricevente_fkey FOREIGN KEY (squadra_ricevente) REFERENCES public.squadra(nome) ON UPDATE CASCADE;
ALTER TABLE public.richiesta_modifica_contratto DROP CONSTRAINT richiesta_modifica_contratto_squadra_richiedente_fkey,
  ADD CONSTRAINT richiesta_modifica_contratto_squadra_richiedente_fkey FOREIGN KEY (squadra_richiedente) REFERENCES public.squadra(nome) ON UPDATE CASCADE;
ALTER TABLE public.scambio DROP CONSTRAINT scambio_squadra_destinataria_fkey,
  ADD CONSTRAINT scambio_squadra_destinataria_fkey FOREIGN KEY (squadra_destinataria) REFERENCES public.squadra(nome) ON UPDATE CASCADE;
ALTER TABLE public.scambio DROP CONSTRAINT scambio_squadra_proponente_fkey,
  ADD CONSTRAINT scambio_squadra_proponente_fkey FOREIGN KEY (squadra_proponente) REFERENCES public.squadra(nome) ON UPDATE CASCADE;

-- Nomi dei vincoli come in prod (rinominare la PK rinomina anche l'indice)
ALTER TABLE public.general_config RENAME CONSTRAINT impostazioni_gate_pkey      TO general_config_pkey;
ALTER TABLE public.general_config RENAME CONSTRAINT impostazioni_gate_singleton TO general_config_singleton;
ALTER TABLE public.transfermarkt_mappa_club RENAME CONSTRAINT mappa_club_transfermarkt_pkey TO transfermarkt_mappa_club_pkey;

-- processa_prestiti_conclusi(): definizione esatta di prod (logica del PR #93,
-- commenti piu' corti di CronJob/cron_job_prestiti.sql): il controllo di
-- sync_dev_db.py confronta il testo intero della funzione.
CREATE OR REPLACE FUNCTION public.processa_prestiti_conclusi()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_limite timestamp := ((NOW() AT TIME ZONE 'Europe/Rome')::date + 1)::timestamp;
  r record;
BEGIN
  -- Riscatti: il giocatore passa alla ricevente, che paga il riscatto alla prestante
  FOR r IN
    SELECT id, giocatore, squadra_prestante, squadra_ricevente,
           COALESCE(crediti_riscatto, 0) AS crediti_riscatto
    FROM prestito
    WHERE data_fine < v_limite
      AND (   (tipo_prestito = 'diritto_di_riscatto' AND stato = 'riscattato')
           OR (tipo_prestito = 'obbligo_di_riscatto'
               AND stato IN ('in_corso', 'richiesta_di_terminazione', 'riscattato')))
    FOR UPDATE
  LOOP
    UPDATE squadra SET crediti = crediti - r.crediti_riscatto WHERE nome = r.squadra_ricevente;
    UPDATE squadra SET crediti = crediti + r.crediti_riscatto WHERE nome = r.squadra_prestante;

    UPDATE giocatore
    SET squadra_att = r.squadra_ricevente,
        detentore_cartellino = r.squadra_ricevente,
        tipo_contratto = 'Indeterminato'
    WHERE id = r.giocatore;

    DELETE FROM vetrina WHERE id_giocatore = r.giocatore;

    UPDATE prestito SET stato = 'terminato', richiedente_terminazione = NULL WHERE id = r.id;
  END LOOP;

  -- Secchi e diritti non esercitati: il giocatore torna alla prestante
  UPDATE giocatore g
  SET squadra_att = p.squadra_prestante,
      tipo_contratto = 'Indeterminato'
  FROM prestito p
  WHERE g.id = p.giocatore
    AND p.tipo_prestito IN ('secco', 'diritto_di_riscatto')
    AND p.stato IN ('in_corso', 'richiesta_di_terminazione')
    AND p.data_fine < v_limite;

  UPDATE prestito
  SET stato = 'terminato',
      richiedente_terminazione = NULL
  WHERE tipo_prestito IN ('secco', 'diritto_di_riscatto')
    AND stato IN ('in_corso', 'richiesta_di_terminazione')
    AND data_fine < v_limite;
END;
$function$;

COMMIT;
